services:
  - type: web
    name: indgpt-web
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.12
